const products = [
  {
    id: 0,
    name: "Honda B16B",
    description: "Dit is een Honda B16B motorblok uit het jaar 1998.",
    current_bid: 53,
    category_name: "Motor onderdelen",
    location: "Utrecht",
    image:
      "https://s1.cdn.autoevolution.com/images/news/gallery/remembering-hondas-legendary-b16-the-engine-that-brought-vtec-to-the-world_11.jpg",
    bids: [
      { amount: 12, user: "John" },
      { amount: 32, user: "Jane" },
      { amount: 45, user: "Bob" },
      { amount: 47, user: "Alice" },
      { amount: 53, user: "Charlie" },
    ],
    end_time: "2023-11-01T14:00:00",
  },
  {
    id: 1,
    name: "Honda S4C",
    description: "Dit is een Honda S4C versnellingsbak uit het jaar 1998.",
    current_bid: 60,
    category_name: "Transmissie onderdelen",
    location: "Arnhem",
    image: "https://img.rnudah.com/grids/28/2833017044277023461.jpg",
    bids: [
      { amount: 30, user: "Mike" },
      { amount: 45, user: "Sarah" },
      { amount: 60, user: "David" },
    ],
    end_time: "2023-11-03T16:30:00",
  },
  {
    id: 2,
    name: "Exedy Stage 1 koppelingsset",
    description: "Dit is een Exedy Stage 1 koppelingsset.",
    current_bid: 70,
    category_name: "Transmissie onderdelen",
    location: "Nijmegen",
    image:
      "https://images.omnitek-labs.com/stage1_clutch_kit/08806fw/08806FW.jpg",
    bids: [
      { amount: 40, user: "Lisa" },
      { amount: 65, user: "Ethan" },
      { amount: 70, user: "Olivia" },
    ],
    end_time: "2023-11-05T12:45:00",
  },
  {
    id: 3,
    name: "SRS 4-2-1 Spruitstuk",
    description: "Dit is een SRS 4-2-1 spruitstuk.",
    current_bid: 35,
    category_name: "Uitlaat",
    location: "Den Haag",
    image:
      "https://www.4-tuner.de/images/product_images/info_images/cvcfkedel421vtec.jpg",
    bids: [{ amount: 35, user: "Sophia" }],
    end_time: "2023-11-07T11:15:00",
  },
  {
    id: 4,
    name: "SRS Catback uitlaat",
    description: "Dit is een SRS Catback uitlaat systeem.",
    current_bid: 40.0,
    category_name: "Uitlaat",
    location: "Rotterdam",
    image:
      "https://www.akr-performance.nl/media/products/uitlaatsysteem-civic-3-deurs-hatchback-1996-1998-14i_srs-catback-uitlaatsysteem-rvs-r60-e-keur-cbs-cv963d-r60.jpg",
    bids: [{ amount: 40, user: "William" }],
    end_time: "2023-11-09T10:30:00",
  },
  {
    id: 5,
    name: "EBC Redstuff remblokken",
    description: "Dit zijn EBC remblokken.",
    current_bid: 42.0,
    category_name: "Remmen",
    location: "Groningen",
    image:
      "https://cdn11.bigcommerce.com/s-6y7pa5d/images/stencil/1280x1280/products/37530/60094/EBC-Redstuff__71241.1589443605.jpg?c=2",
    bids: [{ amount: 42, user: "Mia" }],
    end_time: "2023-11-11T14:45:00",
  },
  {
    id: 6,
    name: "EBC GD Series remschijven",
    description: "Dit zijn EBC remschijven.",
    current_bid: 50.0,
    category_name: "Remmen",
    location: "Leeuwarden",
    image: "https://www.kseriesparts.com/graphics/00000001/ebc-gd_500x333.jpg",
    bids: [{ amount: 50, user: "Daniel" }],
    end_time: "2023-11-13T13:00:00",
  },
  {
    id: 7,
    name: "BC Racing A-03-RH Schroefset",
    description: "Dit is een BC Racing schroefset.",
    current_bid: 55.0,
    category_name: "Ophanging",
    location: "Maastricht",
    image:
      "https://modificars.fi/wp-content/uploads/2022/10/bc-racing-alustasarjat.jpg",
    bids: [{ amount: 55, user: "Nora" }],
    end_time: "2023-11-15T16:15:00",
  },
  {
    id: 8,
    name: "Enkei RPF1 velgen",
    description: "Dit zijn Enkei RPF1 velgen.",
    current_bid: 45.0,
    category_name: "Velgen",
    location: "Eindhoven",
    image:
      "https://cdn11.bigcommerce.com/s-zhf5gt60/images/stencil/1280x1280/products/4888/18347/ENKEI-RPF1-SP-144-WEB__15316.1584822241.jpg?c=2",
    bids: [{ amount: 45, user: "Liam" }],
    end_time: "2023-11-17T15:30:00",
  },
  {
    id: 9,
    name: "Nankang NS-R2 semi-slick banden",
    description: "Dit zijn Nankang NS-2R semi-slick banden.",
    current_bid: 60.0,
    category_name: "Banden",
    location: "Apeldoorn",
    image:
      "https://www.racebanden.nl/wp-content/uploads/2022/02/Nankang-NS-2R_432x484.jpg",
    bids: [{ amount: 60, user: "Sophie" }],
    end_time: "2023-11-19T11:00:00",
  },
  {
    id: 10,
    name: "Momo stuur",
    description: "Dit is een Momo stuur.",
    current_bid: 65.0,
    category_name: "Interieur",
    location: "Zwolle",
    image:
      "https://nl.merlinmotorsport.co.uk/files/resized/medium/V/img/vproherit35.jpg?cachebreak=1059a1b1edee9d8c250050464e698f04",
    bids: [{ amount: 65, user: "Eva" }],
    end_time: "2023-11-21T14:15:00",
  },
  {
    id: 11,
    name: "Bomex Type-R Spoiler",
    description: "Dit is een Bomex Type-R spoiler.",
    current_bid: 70.0,
    category_name: "Exterieur",
    location: "Zutphen",
    image:
      "https://www.a4h-tech.com/media/catalog/product/cache/28d0c30ccc63d3b73999f1cc43728cc2/a/e/ae-sp-cv963d-m-f-aerodynamics-frp-spoiler-bomex-mugen-stijl-civic-96-00-3drs-all4honda.jpg",
    bids: [{ amount: 70, user: "Noah" }],
    end_time: "2023-11-23T16:30:00",
  },
  {
    id: 12,
    name: "OEM Honda blackhousing koplampen",
    description: "Dit zijn OEM Honda blackhousing koplampen.",
    current_bid: 75.0,
    category_name: "Exterieur",
    location: "Amsterdam",
    image:
      "https://m.media-amazon.com/images/I/719Euk7DbIL._AC_UF894,1000_QL80_.jpg",
    bids: [{ amount: 75, user: "Lily" }],
    end_time: "2023-11-25T13:45:00",
  },
  {
    id: 13,
    name: "Luchtverfrisser",
    description: "Dit is een luchtverfrisser.",
    current_bid: 80.0,
    category_name: "Overig",
    location: "Deventer",
    image:
      "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1629745705-turboairfreshener-1629745693.jpg?crop=1xw:1xh;center,top&resize=980:*",
    bids: [{ amount: 80, user: "Mason" }],
    end_time: "2023-11-27T12:30:00",
  },
];

export default products;
